---
title: "Fisher's Discriminant Analysis - Data plot"
output:
  html_document:
    df_print: paged
  word_document: default
---

We will generate a graphic in the following chunk.
```{r}
library(ggplot2)

x <- c(1,-1,0.75,-2,2,2.5,3,0,1,1.5,4,2)
y <- c(1,0.5,-1,-2,1.5,2.4,1.8,4,4,4.2,4, 4.5)
df <- data.frame(cbind(x, y))

colors= c(0,0,0,0,1,1,1,1,2,2,2,2)
g <- ggplot(data = df, aes(x = df$x, y = df$y, colour=factor(colors))) + geom_point()

g <- g + geom_point(alpha = 1/3)  # alpha b/c of overplotting
g <- g + coord_fixed()
```

```{r show_figure}
# corre <- cor(x = df$x, y = df$y, method = "spearman")  # calculate correlation, must be spearman b/c of measurement
# matrix <- matrix(c(1, corre, corre, 1), nrow = 2)  # make this into a matrix
# eigen <- eigen(matrix)  # calculate eigenvectors and values
# eigen$vectors.scaled <- eigen$vectors %*% diag(sqrt(eigen$values))
# 
# g <- g + geom_abline(intercept = eigen$values[1], slope = 1, colour = "yellow")  # add slope for pc1
# g <- g + geom_abline(intercept = eigen$values[2], slope = -1, colour = "violet")  # add slope for pc2
# 
# g
```
```{r}

perp.segment.coord <- function(x0, y0, a=0,b=1){
  #finds endpoint for a perpendicular segment from the point (x0,y0) to the line
  # defined by lm.mod as y=a+b*x
  x1 <- (x0+b*y0-a*b)/(1+b^2)
  y1 <- a + b*x1
  list(x0=x0, y0=y0, x1=x1, y1=y1)
}

```


```{r}

g1=g+geom_segment(aes(x=-1,y=5,xend=4,yend=5), arrow=arrow(length = unit(0.03, "npc")))
#Orthogonal projection

ss2<-perp.segment.coord(df$x, df$y, 5, 0)

g1 + geom_segment(data=as.data.frame(ss2), aes(x = x0, y = y0, xend = x1, yend = y1), colour = "black")
```
```{r}
g=g+ geom_segment(aes(x = -2, y = -1, xend = 3, yend = 5), arrow = arrow(length = unit(0.03, "npc")), label="L2")
ss1<-perp.segment.coord(df$x, df$y, 1.4, 1.2)

g + geom_segment(data=as.data.frame(ss1), aes(x = x0, y = y0, xend = x1, yend = y1), colour = "gray")

```

```{r}

x <- c(-2, -3, -2.5, -1, 1, 2, 2, 0, -1, 0, -2)
y <- c(-4, -5, -2.5, -6, -3, -2, -4, -2, 1, 2, 3)
df <- data.frame(cbind(x, y))

colors= c(0,0,0,0,1,1,1,1,2,2,2)
g2 <- ggplot(data = df, aes(x = df$x, y = df$y, colour=factor(colors))) + geom_point()

g2 <- g2 + geom_point(alpha = 1/3)  # alpha b/c of overplotting
g2 <- g2 + coord_fixed()

g3=g2+geom_segment(aes(x=-2,y=6,xend=6,yend=-6), arrow=arrow(length = unit(0.03, "npc")))
ss1<-perp.segment.coord(df$x, df$y, 3, -1.5)
g3 + geom_segment(data=as.data.frame(ss1), aes(x = x0, y = y0, xend = x1, yend = y1), colour = "gray")

g3
```

```{r}

g2=g2+geom_segment(aes(x=-6,y=-4,xend=2,yend=2), arrow=arrow(length = unit(0.03, "npc")))
ss1<-perp.segment.coord(df$x, df$y, 0.5, 0.75)
g2 + geom_segment(data=as.data.frame(ss1), aes(x = x0, y = y0, xend = x1, yend = y1), colour = "gray")

```

